dist: xenial # Python3.4 for trusty Python3.5 for xenial

group: edge

language: java

sudo: required

jdk: openjdk8

env:
  - SCRIPT=travis-openjdk8.sh
  - SCRIPT=travis-oraclejdk8.sh
  - SCRIPT=travis-coverage.sh
  - SCRIPT=travis-jar.sh
#  - SCRIPT=travis-dspot-maven.sh
  - SCRIPT=travis-checkstyle.sh
  - SCRIPT=travis-dhell.sh
  - SCRIPT=travis-ci-xwiki.sh
  - SCRIPT=travis-diff-test-selection.sh
  - SCRIPT=travis-prettifier.sh
#  - SCRIPT=travis-dspot-maven-cmd-line.sh TODO FIX ME

cache:
  directories:
  - $HOME/.m2

before_install:
- sudo apt-get update
- sudo apt-get install python3
- sudo apt-get install python3-pip
- sudo apt-get install python3-setuptools
# Pull Mongodb image to test
- docker pull mongo:latest
- docker run -d --net=host mongo:latest

install:
- export DSPOT_VERSION=`grep '<version>' dspot/pom.xml | head -n 1 | sed -e 's/<version>//' -e 's/<\\/version>//' -e 's/ *//g'`
- export MAVEN_HOME=`mvn --version | grep 'Maven home' | sed -e 's/Maven h.* //'`
- mvn compile --quiet
- cd dspot && ./src/main/bash/update-classes-in-resources.sh
- cd ..
- mvn install -DskipTests -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true
- python3 --version
- which python3

script:
- ./.travis/$SCRIPT $DSPOT_VERSION

after_success:
- ./.travis/travis-deploy.sh

branch:
  only:
  - master
